services:
  - type: web
    name: teamOKITO
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn teamOKITO.app:app --bind 0.0.0.0:$PORT --chdir teamOKITO
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BUILD_NUMBER
        value: ${BUILD_NUMBER}
      - key: DEPLOYMENT_DATE
        value: ${DEPLOYMENT_DATE}
